# Generated by Django 5.2.17 on 2026-09-22 22:40

import apps.mural.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_institution_alter_document_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuralPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=2000, verbose_name='texto')),
                ('status', models.CharField(choices=[('visible', 'Visível'), ('hidden', 'Oculta'), ('removed', 'Removida')], default='visible', max_length=9, verbose_name='status')),
                ('report_count', models.PositiveIntegerField(default=0, verbose_name='denúncias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='editado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mural_posts', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mural.muralpost', verbose_name='publicação original')),
            ],
            options={
                'verbose_name': 'publicação do mural',
                'verbose_name_plural': 'publicações do mural',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuralAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'Arquivo'), ('link', 'Link'), ('document', 'Documento do acervo')], max_length=9, verbose_name='tipo')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.mural.models.mural_upload_path, verbose_name='arquivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='tipo mime')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='url')),
                ('link_title', models.CharField(blank=True, max_length=255, verbose_name='título do link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mural_attachments', to='documents.document', verbose_name='documento do acervo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mural.muralpost', verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'anexo do mural',
                'verbose_name_plural': 'anexos do mural',
            },
        ),
        migrations.CreateModel(
            name='MuralReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Ofensivo'), ('copyright', 'Direitos autorais'), ('other', 'Outro')], max_length=20, verbose_name='motivo')),
                ('details', models.TextField(blank=True, verbose_name='detalhes')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('kept', 'Mantida'), ('hidden', 'Ocultada')], default='pending', max_length=9, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revisado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mural.muralpost', verbose_name='publicação')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mural_reports', to=settings.AUTH_USER_MODEL, verbose_name='denunciante')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mural_reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
            ],
            options={
                'verbose_name': 'denúncia do mural',
                'verbose_name_plural': 'denúncias do mural',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='muralpost',
            index=models.Index(fields=['status', '-created_at'], name='mural_mural_status_d117dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='muralreport',
            constraint=models.UniqueConstraint(fields=('post', 'reporter'), name='unique_mural_report'),
        ),
    ]
