# Generated by Django 5.2.17 on 2026-09-11 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="arquivo avulso"
                    ),
                ),
                ("prompt", models.TextField(verbose_name="pergunta")),
                ("answer", models.TextField(blank=True, verbose_name="resposta")),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="modelo"),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tempo de resposta (ms)"
                    ),
                ),
                (
                    "truncated",
                    models.BooleanField(
                        default=False, verbose_name="documento truncado"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="data"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_queries",
                        to="documents.document",
                        verbose_name="documento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta de IA",
                "verbose_name_plural": "consultas de IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
