# Generated by Django 5.2.17 on 2026-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_terms_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="aceitou os termos em"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_terms_version",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="versão dos termos aceita"
            ),
        ),
    ]
