# Generated by Django 5.2.17 on 2026-09-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accepted_terms_at_user_accepted_terms_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor'), ('moderator', 'Moderador'), ('manager', 'Gestor'), ('admin', 'Administrador')], default='student', max_length=20, verbose_name='perfil'),
        ),
    ]
