# Generated by Django 5.2.17 on 2026-09-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="descrição"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="nome"),
                ),
                (
                    "acronym",
                    models.CharField(blank=True, max_length=20, verbose_name="sigla"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
            ],
            options={
                "verbose_name": "instituição",
                "verbose_name_plural": "instituições",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="nome"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=70,
                        unique=True,
                        verbose_name="identificador",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="academics.institution",
                        verbose_name="instituição",
                    ),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.course",
                        verbose_name="curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "disciplina",
                "verbose_name_plural": "disciplinas",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("institution", "name"), name="unique_course_per_institution"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="unique_subject_per_course"
            ),
        ),
    ]
