# Generated by Django 5.2.17 on 2026-09-22 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('public', 'Pública'), ('private', 'Privada')], default='public', max_length=10, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='SubjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor')], default='student', max_length=10, verbose_name='papel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academics.subject', verbose_name='disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'vínculo com disciplina',
                'verbose_name_plural': 'vínculos com disciplina',
                'ordering': ['subject', 'user'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'user'), name='unique_subject_member')],
            },
        ),
    ]
