# Generated by Django 5.2.17 on 2026-09-11 20:14

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "material_author",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="autor do material"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.document_upload_path,
                        verbose_name="arquivo",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="nome original do arquivo",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="tamanho do arquivo (bytes)"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Privado"), ("public", "Público")],
                        default="private",
                        max_length=10,
                        verbose_name="visibilidade",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publicado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="academics.category",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dono",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="academics.subject",
                        verbose_name="disciplina",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="academics.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["visibility", "-published_at"],
                        name="documents_d_visibil_a09b76_idx",
                    )
                ],
            },
        ),
    ]
