# Generated by Django 5.2.17 on 2026-09-22 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_institution_type_subjectmember'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='academics.institution', verbose_name='instituição'),
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('community', 'Comunidade'), ('restricted', 'Restrito')], default='community', max_length=10, verbose_name='visibilidade'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visibility', 'restricted'), _negated=True), ('subject__isnull', False), _connector='OR'), name='document_restricted_requires_subject'),
        ),
    ]
